# Generated by Django 3.2 on 2021-05-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('associatedcompanyid', models.IntegerField(blank=True, db_column='AssociatedCompanyID', null=True)),
                ('roleproperty', models.CharField(blank=True, db_column='RoleProperty', max_length=255, null=True)),
                ('property', models.CharField(blank=True, db_column='Property', max_length=255, null=True)),
                ('puspartnerno', models.CharField(blank=True, db_column='PUSpartnerNo', max_length=255, null=True)),
                ('pusname', models.CharField(blank=True, db_column='PUSname', max_length=255, null=True)),
                ('companyno', models.CharField(blank=True, db_column='companyNo', max_length=255, null=True)),
                ('companyname', models.CharField(blank=True, db_column='companyName', max_length=255, null=True)),
                ('companyname_cn', models.CharField(blank=True, db_column='companyName_CN', max_length=255, null=True)),
                ('shortname', models.CharField(blank=True, db_column='shortName', max_length=255, null=True)),
                ('innerused', models.CharField(blank=True, db_column='innerUsed', max_length=5, null=True)),
                ('currency', models.CharField(blank=True, db_column='Currency', max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, db_column='Language Code', max_length=255, null=True)),
                ('date_created', models.DateTimeField(blank=True, db_column='Date Created', null=True)),
                ('timeupdated', models.DateTimeField(blank=True, db_column='TimeUpdated', null=True)),
                ('expiry_date', models.DateTimeField(blank=True, db_column='Expiry Date', null=True)),
                ('original', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('detailaddress', models.CharField(blank=True, db_column='detailAddress', max_length=255, null=True)),
                ('buyer', models.CharField(blank=True, db_column='Buyer', max_length=255, null=True)),
                ('doc', models.CharField(blank=True, max_length=255, null=True)),
                ('lastdoc', models.CharField(blank=True, db_column='lastDoc', max_length=255, null=True)),
                ('defaulttask', models.IntegerField(blank=True, db_column='defaultTask', null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('samesupplieridentity', models.CharField(blank=True, db_column='SameSupplierIdentity', max_length=255, null=True)),
                ('quality_approved', models.CharField(blank=True, db_column='Quality Approved', max_length=255, null=True)),
                ('quality_date', models.DateTimeField(blank=True, db_column='Quality Date', null=True)),
                ('quality_type', models.CharField(blank=True, db_column='Quality Type', max_length=255, null=True)),
                ('quality_note_text', models.CharField(blank=True, db_column='Quality Note Text', max_length=255, null=True)),
                ('taxnumber', models.CharField(blank=True, db_column='taxNumber', max_length=255, null=True)),
                ('historictaxnumber', models.CharField(blank=True, db_column='historicTaxNumber', max_length=255, null=True)),
                ('environment_approved', models.CharField(blank=True, db_column='Environment Approved', max_length=255, null=True)),
                ('environment_date', models.CharField(blank=True, db_column='Environment Date', max_length=255, null=True)),
                ('environment_type', models.DateTimeField(blank=True, db_column='Environment Type', null=True)),
                ('environment_note_text', models.CharField(blank=True, db_column='Environment Note Text', max_length=255, null=True)),
                ('code_of_conduct_approved', models.CharField(blank=True, db_column='Code of Conduct Approved', max_length=255, null=True)),
                ('code_of_conduct_date', models.DateTimeField(blank=True, db_column='Code of Conduct Date', null=True)),
                ('code_of_conduct_type', models.CharField(blank=True, db_column='Code of Conduct Type', max_length=255, null=True)),
                ('code_of_conduct_note_text', models.CharField(blank=True, db_column='Code of Conduct Note Text', max_length=255, null=True)),
                ('pay_term_id', models.CharField(blank=True, db_column='Pay Term ID', max_length=255, null=True)),
                ('pay_tax', models.CharField(blank=True, db_column='Pay Tax', max_length=255, null=True)),
                ('pay_term_info', models.CharField(blank=True, db_column='Pay Term Info', max_length=255, null=True)),
                ('pay_tax_info', models.CharField(blank=True, db_column='Pay Tax Info', max_length=255, null=True)),
                ('rowcreatedtime', models.DateTimeField(blank=True, db_column='rowCreatedTime', null=True)),
                ('rowupdatedtime', models.DateTimeField(blank=True, db_column='rowUpdatedTime', null=True)),
                ('aidselection', models.CharField(blank=True, db_column='aidSelection', max_length=5, null=True)),
                ('ownplant', models.CharField(blank=True, db_column='ownPlant', max_length=5, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountryArea',
            fields=[
                ('id_upper', models.PositiveIntegerField(blank=True, db_column='ID_upper', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('no', models.IntegerField(blank=True, db_column='No', null=True)),
                ('en_name', models.CharField(blank=True, db_column='EN_name', max_length=255, null=True)),
                ('cn_name', models.CharField(blank=True, db_column='CN_name', max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, db_column='Country Code', max_length=5, null=True)),
                ('system_defined', models.CharField(blank=True, db_column='System Defined', max_length=1, null=True)),
                ('id_co_oper', models.PositiveIntegerField(db_column='ID_co_oper')),
            ],
            options={
                'db_table': 'country_cn_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'UserType',
                'managed': False,
            },
        ),
    ]
