# Generated by Django 3.2 on 2021-07-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('curr_description', models.CharField(blank=True, max_length=255, null=True)),
                ('factor', models.FloatField(db_column='Factor')),
                ('base_currency', models.CharField(max_length=10)),
                ('active_status', models.CharField(max_length=11)),
                ('id_co_oper', models.PositiveIntegerField(db_column='ID_co_oper')),
            ],
            options={
                'db_table': 'currency',
                'managed': False,
            },
        ),
    ]
